import Navbar from "@/components/Navbar";
import "./globals.css";
import "boxicons/css/boxicons.min.css";
import { CartProvider } from "@/CartContext";
import { Providers } from "./providers";

export const metadata = {
  title: "E-commerce Store",
  description: "Generated by Abiola Emmanuel",
};

export default function RootLayout({ children }) {
  return (

    <CartProvider>
      <html lang="en">
        <body>
          <Providers>
            <Navbar />
            {children}
          </Providers>
        </body>
      </html>
    </CartProvider>
  );
}
